# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
  schedule:
    - cron: '50 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: '[Prepare] Set Python'
        uses: actions/setup-python@v1
        with: 
          python-version: '3.8.12'
      - name: '[Prepare] Install Dependencies'
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade requests==2.24.0
          python -m pip install --upgrade bs4
      # Runs a single command using the runners shell
      - name: '[Main] Check in'
        run: |
          python test.py
